#系统启动端口
server:
  port: 8081

#指定当前环境（开发环境dev；生产环境prod）
spring.profiles.active: dev

#数据库环境信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.199.102:3306/jj_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    url: jdbc:mysql://101.133.132.110:3306/jj_admin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: HpAnstxx5ahmySYK

#spring集成Mybatis环境
mybatis:
  configLocation: classpath:mybatis-config.xml
  #pojo别名扫描包
  type-aliases-package: com.shengming.entity
  #加载Mybatis映射文件
  mapper-locations: classpath:mapper/*Mapper.xml

